### ISSUE TITLE
Greeting and starting the feedback process

### ISSUE THREAD

**Issue by sleepylee** [zinzem/survey#2]
Hi Ruben,
It's Trung (again) that you met a few days ago. :-)
First of all, I'd like to say thanks for your times and efforts on completing the assignment. As the next step, I and the team will provide you our comments through Issues we open. 
Please keep in mind, that our code review process is not about policing candidates, but open for discussion and learning purpose. There are multiple implementation ways that can be done and we always respect the candidate's original ideas, but there is also a need for evaluation based on what sounds right or not from the technical perception.
So please go ahead and raise your voice if any of our comment isn't right or if you need further clarifications. If you do feel the need of patching according to our comment, kindly open PR correspondingly and merge whenever you feel they are good to go.

The first issue we'd raise is about the overall application design: it doesn't look so right to the requirements we gave. To be clear: the small image from the requirement can't be enough to use as a proper specs design I understand so we don't expect 100% precision here. What I mean here is the overall structure of it: the action bar structure, the indicators positioning... they look off totally from what we would expect (said from the requirements):

<img src= "https://user-images.githubusercontent.com/13435717/57071073-837f5380-6d03-11e9-942b-6fc38cf8b028.png" width=200/> <img src="https://user-images.githubusercontent.com/13435717/57071090-8f6b1580-6d03-11e9-9184-076d20c1784e.png" width=200 height=300/>

**Comment by zinzem** [comment]
Fair enough. The idea was to make it a bit more "modern", but I get your point. Will update.
