### ISSUE TITLE
The application only has "happy path" implementations

### ISSUE THREAD

**Issue by sleepylee** [zinzem/survey#5]
- There is no error handler, the network request is designed to be silent on catching errors.
- Testing is also designed to test only positive cases. A bit more diving into integration tests (for e.g authentication flow) would be great to have)

**Comment by zinzem** [comment]
- Well, as there was no mention of error handling, I chose the easiest path.
Would you prefer some SnackBar?
- You're right, Let me add a unit test for the authentication flow

**Comment by sleepylee** [comment]
hi @zinzem, for error handling let's just handle it simply with a Toast, my intention is just want to see how error/network errors are getting caught in general. At the end side, popping it up by any type of UI doesn't matter much to us as they are not in the requirement. 
Also, I agree on the point where we haven't put it on the docs, hence your choice was the easiest path to complete, but tbh in the real-life application, error handling should be common to get designed at first no? ;)
